//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Skak.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IHelloService", CallbackContract=typeof(Online_Skak.Service.IHelloServiceCallback))]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/GetMessage")]
        void GetMessage();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/GetMessage")]
        System.Threading.Tasks.Task GetMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/IncrementNumber", ReplyAction="http://tempuri.org/IHelloService/IncrementNumberResponse")]
        int IncrementNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/IncrementNumber", ReplyAction="http://tempuri.org/IHelloService/IncrementNumberResponse")]
        System.Threading.Tasks.Task<int> IncrementNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Subscribe", ReplyAction="http://tempuri.org/IHelloService/SubscribeResponse")]
        System.Guid Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Subscribe", ReplyAction="http://tempuri.org/IHelloService/SubscribeResponse")]
        System.Threading.Tasks.Task<System.Guid> SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/BroadCast")]
        void BroadCast(System.Guid clientId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/BroadCast")]
        System.Threading.Tasks.Task BroadCastAsync(System.Guid clientId, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/Progress")]
        void Progress(int percentageComplete);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHelloService/HandleMessage")]
        void HandleMessage(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : Online_Skak.Service.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.DuplexClientBase<Online_Skak.Service.IHelloService>, Online_Skak.Service.IHelloService {
        
        public HelloServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public HelloServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public HelloServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetMessage() {
            base.Channel.GetMessage();
        }
        
        public System.Threading.Tasks.Task GetMessageAsync() {
            return base.Channel.GetMessageAsync();
        }
        
        public int IncrementNumber() {
            return base.Channel.IncrementNumber();
        }
        
        public System.Threading.Tasks.Task<int> IncrementNumberAsync() {
            return base.Channel.IncrementNumberAsync();
        }
        
        public System.Guid Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task<System.Guid> SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void BroadCast(System.Guid clientId, string message) {
            base.Channel.BroadCast(clientId, message);
        }
        
        public System.Threading.Tasks.Task BroadCastAsync(System.Guid clientId, string message) {
            return base.Channel.BroadCastAsync(clientId, message);
        }
    }
}
